### ISSUE TITLE
Small wishes

### ISSUE THREAD

**Issue by grylem** [ololx/quick-symlink#9]
Привет,
будет здорово, если вы сможете добавить:
английскую локализацию
отображение иконок в контекстном меню
возможность отключения именно контекстного меню.
объединить контекстное меню для ссылок.
сделать иконки(finder toolbar) более подходящими для Big Sur.
С уважением.

**Comment by ololx** [comment]
Добрый день, 
Спасибо за обратную связь. Я обязательно все изучу и дам Вам развернутый ответ по Вашему предложению.
Но уже сейчас могу сказать следующее:
1 - Английская локализация уже существует, однако я для нее указан все наименования на русском языке - это баг, который Вы заметили и я его исправлю сегодня - завтра.
2 - По поводу остальных пунктов я отвечу Вам на выходных, но скорее всего я реализую все Ваши предложения, кроме "объединить контекстное меню для ссылок"; "объединить контекстное меню для ссылок" - кажется не очень удобным с точки зрения пользования (если имеется ввиду именно контекстное меню по правому клику мыши). Однако Вы можете переубедить меня, елси покажете мне дизайн такого меню (как Вы предлагаете).

**Comment by ololx** [comment]
Исправил баг с локализацией - пожалуйста проверьте версию 0.10.1. Если поменять в системных настройках язык с Русского на Английский - то пункты меню должны отображаться уже в Английской локализации.

**Comment by grylem** [comment]
> Вы можете переубедить меня, елси покажете мне дизайн такого меню (как Вы предлагаете).

я и на остальных пунктах не настаиваю - предпочитаю для этих целей ком. строку. Просто показалось что тогда можно будет сократить дублирующиеся - copy/paste link...

> Исправил баг с локализацией

вместо hardlink actions - alias actions, это вносит путанницу т.к. под alias в finder понимается другое.

Если возможно, то не помешало бы добавить авторизацию , с целью создания ссылок в папках требующих прав администратора.

**Comment by ololx** [comment]
Тогда все еще проще, сегодня переименую пункт меню - остальное сделаю уже позже; пока занят на основной работе.
Еще раз спасибо за дельные предложения, особенно с авторизацией.

**Comment by grylem** [comment]
Если есть интерес в расширении функцинала, можно добавить - заменить ссылку с абсолютным путем на относительный, исправить неверную ссылку и/или проверить ее на соответствие, заменить symlink на hardlink и  наоборот, добавить unhardlink и  т.д.

**Comment by grylem** [comment]
Может есть смысл сделать полноценную программу для работы с finder alias, symlinks, hardlinks в которой finder extensions будут только частью программы? Набор операций не такой уж большой и тогда контекстное меню не будет перегруженным.
